menu:
#  Home: /
  Archives: /archives
#  Reading: /reading
  About: /about
#  Guestbook: /about

excerpt_link: Read More
archive_yearly: true

widgets:
  - category
#  - tag
  - tagcloud
  - recent_posts
#  - blogroll

blogrolls:
#  - bruce MoGeek's hexo blog: https://owlwinter.github.io

fancybox: true

duoshuo_shortname: buru

google_analytics: false
baidu_tongji: false

rss: /atom.xml
